// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loesukbxbrxrxzrcakeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvZXN1a2J4YnJ4cnh6cmNha2VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5ODcwNjYsImV4cCI6MjA1ODU2MzA2Nn0.ljXbuOoaaoDLQWT7yX_WCtKc9yZH7iEUF5qh7MY8f78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);